const I18N = {
  banks: ['Krungthai Bank','Bangkok Bank','Kasikorn Bank','Siam Commercial Bank','Bank of America','Citibank','HSBC','Wells Fargo','Chase','Barclays'],
  anonRules: [[/(Mr\.|Mrs\.|Ms\.|Miss)\s?[A-Z][a-zA-Z]{2,}/g, '[PERSON_TOKEN]']],
  workStyles: ['Sedentary / Desk Work (sitting at a desk all day)','Active / On the move (frequent travel/movement)','Hybrid Work (alternating desk work and meetings)'],
  defaultTasks: [
    { title: 'Cardio exercise', duration: 45, priority: 'High' },
    { title: 'Self-development reading', duration: 30, priority: 'Medium' },
    { title: 'Meditation / breathing practice', duration: 15, priority: 'Medium' },
    { title: 'Time with family / friends', duration: 45, priority: 'Low' }
  ],
  presets: [
    { title: 'Exercise', duration: 45, priority: 'Medium', type: 'Personal' },
    { title: 'Self-development reading', duration: 30, priority: 'Low', type: 'Personal' },
    { title: 'Meditation / breathing practice', duration: 15, priority: 'Low', type: 'Personal' },
    { title: 'Cooking / meal prep', duration: 45, priority: 'Medium', type: 'Personal' },
    { title: 'Time with family / friends', duration: 60, priority: 'Medium', type: 'Personal' },
    { title: 'Pet care', duration: 20, priority: 'Low', type: 'Personal' },
    { title: 'Hobby (music / drawing / gaming)', duration: 30, priority: 'Low', type: 'Personal' },
    { title: 'Nap / short rest', duration: 20, priority: 'Low', type: 'Personal' }
  ],
  sched: {
    min: 'min', shortened: '(shortened)', adjSuffix: ' (adjusted)',
    reasonFatigue: (n) => `High accumulated fatigue (${n}/10) — shortened to prevent burnout`,
    reasonLimited: (w) => `Limited free time in the ${w}`,
    morning: 'morning', evening: 'evening',
    wake: 'Wake up & Morning Stretch', breakfast: 'Breakfast',
    freeMorning: 'Free time (morning) — rest / get ready',
    commuteTo: 'Commute to work', commuteHome: 'Commute home',
    work: 'Work (your own schedule)', untouched: 'Untouched',
    skipped: 'Skipped (no time slot)',
    skipReason: 'Not enough free time outside work hours to fit this activity in full. Try reducing the number of activities or adjusting your wake/sleep times.',
    dinner: 'Dinner & personal free time', detox: 'Digital Detox & wind down for bed'
  },
  ui: {
    navWizard: 'Setup Wizard', navDash: 'Life Dashboard', navPrivacy: 'Privacy & AI Settings',
    noSchedule: 'No schedule to download yet', noPrint: 'No schedule to print yet',
    txtTitle: 'Daily Schedule — AI Life Planner',
    txtCuts: 'Activities automatically adjusted (Smart Cut):'
  },
  wizard: {
    title: 'Daily Life Planning Questionnaire',
    subtitle: 'Enter your schedule, physical condition, and workload so the system can calculate the most suitable timetable.',
    s1Title: '1. Daily Routine & Work Schedule',
    wake: 'Wake-up time', sleep: 'Bedtime', workStart: 'Work start', workEnd: 'Work end',
    phWake: 'e.g. 0630', phSleep: 'e.g. 2300', phWorkStart: 'e.g. 0900', phWorkEnd: 'e.g. 1800',
    travel: 'Commute time (one-way, minutes)',
    travelHint: "Used to work out when you need to leave and when you'll get home (one-way value, applied to both directions).",
    workNote: 'ℹ️ The "Work start–Work end" range is reserved as a single <strong>"Work"</strong> block. The system will never insert meetings, activities, or breaks into this time, since you already run your own work schedule — everything in the next step is only ever placed in the free time "before work" or "after work".',
    workStyle: 'Work style',
    next1: 'Next: Energy & Physical Assessment',
    s2Title: '2. Body & Fatigue Assessment (Energy & Stress Sliders)',
    energy: 'Physical energy level:', fatigue: 'Accumulated fatigue:', stress: 'Accumulated stress:',
    back: 'Back', next2: 'Next: Activities & Tasks',
    s3Title: '3. Off-Work Activities to Schedule',
    s3Hint: 'Only add personal / self-development activities you want to do "before work" or "after work" — no need to add work tasks, meetings, or emails, since your work hours are reserved as a single untouched block.',
    whenTitle: 'Preferred window', auto: 'Auto', morning: 'Morning', evening: 'Evening', remove: 'Remove this activity',
    noTasks: 'No activities yet — add some from the examples below.',
    autoHint: '"Auto" lets the system pick whichever window has more free time left. "Morning"/"Evening" pins the activity to that window only.',
    presets: 'Pick from example activities (click to add instantly)', minShort: 'm',
    custom: 'Or add a custom activity', customPh: 'Activity name, e.g. band practice', addTask: 'Add activity'
  },
  dash: {
    badgeLoading: 'Processing...', badgeAi: 'Generated by AI (Claude via your API key)',
    badgeOffline: 'Offline mode (rule-based — no API key set)',
    readiness: 'Physical readiness today',
    fatigueHigh: '⚠️ Schedule intensity reduced to prevent burnout', fatigueOk: '✓ Fatigue level is within a healthy range',
    workHours: 'Work hours (as you specified)', hours: 'hours',
    workReserved: '✓ Reserved as a single block — never split or altered by the system',
    cutNote: 'Adjusts timing without skipping important goals', reason: 'Reason:',
    scheduleTitle: 'Smart Life Schedule (Time-Blocking Schedule)',
    pdf: 'PDF (print)', cal: 'Calendar (.ics)',
    alloc: 'Time Allocation by Category',
    recs: 'Personalized 4-Dimension Recommendations', generating: 'Generating personalized recommendations...'
  },
  privacy: {
    shieldSub: 'A personal-data protection and substitution system (Anonymization Layer) — runs for real in your browser before anything is sent to AI.',
    tableTitle: 'Your current activity list ➔ what the system actually sends to AI',
    raw: 'Raw data', anon: 'After anonymization', empty: 'No activities in your list yet',
    shieldNote: 'Anonymization always happens in your browser before any AI call is made. Raw data never leaves your device, and the schedule computed by the local algorithm works with no AI at all (AI is only used to enrich the recommendations).',
    aiTitle: 'Enable real AI (optional)',
    aiSub: 'Add your own Anthropic API key so Claude can write specific 4-dimension recommendations, instead of the rule-based fallback used by default.',
    save: 'Save key', clear: 'Clear key',
    keyFound: '✓ Found an API key saved in this browser. The system will call the real Claude API next time you click Generate.',
    keyNone: 'Not set yet — the system will keep using rule-based fallback recommendations.',
    keyWarn: "Your key is stored only in this browser's <code>localStorage</code> and sent directly from your browser to the Anthropic API — no other server is involved. This is fine for personal use on a device you trust, but this key should not be used on a page published for other people to share."
  },
  fallback: (f) => ({
    fitness: `Work style: ${f.workStyle.split('(')[0].trim()}. Recommend a desk stretch / posture correction every 2 hours, and scale exercise intensity to your fatigue level (${f.fatigue}/10).`,
    nutrition: `Your energy level is ${f.energy}/10. Rest your eyes and hydrate every 2 hours, and keep mealtimes consistent to maintain energy throughout the day.`,
    mental: `Your accumulated stress is ${f.stress}/10. Add a short 4-7-8 breathing exercise in the afternoon to lower cortisol.`,
    growth: `Use short free moments while commuting or on breaks for micro-learning — a podcast or short article instead of long reading sessions.`
  }),
  buildPrompt: (f, anonTasks, cuts) =>
    'You are an AI Life Design & Schedule Architect, an expert in time allocation, fatigue reduction, and stress management.\n\n' +
    'User data (personal information has already been removed by the anonymization system):\n' +
    '- Energy level: ' + f.energy + '/10, accumulated fatigue: ' + f.fatigue + '/10, accumulated stress: ' + f.stress + '/10\n' +
    '- Work style: ' + f.workStyle + '\n' +
    '- Activity list: ' + anonTasks.join(' | ') + '\n' +
    '- Activities automatically shortened by Smart Cut: ' + (cuts.map((c) => c.task + ' -> ' + c.adjusted).join(' | ') || 'None') + '\n\n' +
    'Please suggest short recommendations (1-2 sentences per item, specific to the data above, not generic advice) across 4 dimensions. ' +
    'Respond in JSON only, with no explanation outside the JSON, in this format: {"fitness": "...", "nutrition": "...", "mental": "...", "growth": "..."}'
};
// =========================================================================
// Shared logic (identical for TH and EN). Text comes from I18N (see top of file).
// =========================================================================
const icon = (path, size = 20) =>
  `<svg class="icon" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${path}</svg>`;
const Icons = {
  calendar: icon('<rect x="3" y="4" width="18" height="18" rx="2"/><path d="M16 2v4M8 2v4M3 10h18"/>'),
  clock: icon('<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/>'),
  dumbbell: icon('<path d="M6.5 6.5 17.5 17.5"/><path d="m21 21-1-1M4 4 3 3M18 18l-2-2M8 8 6 6"/><path d="M3.5 8.5 8.5 3.5"/><path d="m15.5 20.5 5-5"/>'),
  heart: icon('<path d="M19 14c1.5-1.5 3-3.28 3-5.5A5.5 5.5 0 0 0 12 6a5.5 5.5 0 0 0-10 2.5C2 10.5 3.5 12.5 5 14l7 7Z"/><path d="M3.22 9H9.5l1.5-2 2 4 1-2h6.28"/>'),
  brain: icon('<path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96.5A2.5 2.5 0 0 1 4.96 17H4.5A2.5 2.5 0 0 1 2 14.5v-1a2.5 2.5 0 0 1 1.5-2.29A2.5 2.5 0 0 1 5 6.5A2.5 2.5 0 0 1 9.5 2Z"/><path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96.5A2.5 2.5 0 0 0 19.04 17h.46a2.5 2.5 0 0 0 2.5-2.5v-1a2.5 2.5 0 0 0-1.5-2.29A2.5 2.5 0 0 0 19 6.5A2.5 2.5 0 0 0 14.5 2Z"/>'),
  shield: icon('<path d="M12 22s8-4 8-11V5l-8-3-8 3v6c0 7 8 11 8 11Z"/>'),
  sparkles: icon('<path d="M12 3v4M12 17v4M3 12h4M17 12h4M5.6 5.6l2.8 2.8M15.6 15.6l2.8 2.8M18.4 5.6l-2.8 2.8M8.4 15.6l-2.8 2.8"/>'),
  alert: icon('<path d="M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0Z"/><path d="M12 9v4M12 17h.01"/>'),
  refresh: icon('<path d="M21 12a9 9 0 1 1-3-6.7"/><path d="M21 3v6h-6"/>'),
  zap: icon('<path d="M13 2 3 14h7l-1 8 10-12h-7l1-8Z"/>'),
  arrow: icon('<path d="M5 12h14M13 6l6 6-6 6"/>', 16),
  download: icon('<path d="M12 3v12m0 0 4-4m-4 4-4-4"/><path d="M4 17v2a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-2"/>', 16),
  plus: icon('<path d="M12 5v14M5 12h14"/>', 16),
  trash: icon('<path d="M3 6h18M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2m2 0-1 14a2 2 0 0 1-2 2H9a2 2 0 0 1-2-2L6 6"/>', 14),
  robot: icon('<rect x="4" y="8" width="16" height="12" rx="2"/><path d="M12 2v6M9 13h.01M15 13h.01"/>'),
  key: icon('<circle cx="7.5" cy="15.5" r="5.5"/><path d="m21 2-9.6 9.6M15.5 7.5 19 11l3-3-3.5-3.5"/>', 16)
};

function anonymize(text) {
  if (!text) return text;
  let out = String(text);
  I18N.banks.forEach((b) => { out = out.split(b).join('[BANK_TOKEN]'); });
  I18N.anonRules.forEach(([re, tok]) => { out = out.replace(re, tok); });
  out = out.replace(/\b[A-Z][a-z]+\s[A-Z][a-z]+\b/g, '[PERSON_TOKEN]');
  out = out.replace(/[A-Z][A-Za-z]*\s?(Corp\.?|Co\.,?\s?Ltd\.?|Inc\.?|Company)/g, '[ORG_TOKEN]');
  return out;
}

// ---------------- Scheduling engine ----------------
function toMin(t) { const [h, m] = t.split(':').map(Number); return h * 60 + m; }
function fmtTime(m) {
  m = ((m % 1440) + 1440) % 1440;
  return String(Math.floor(m / 60)).padStart(2, '0') + ':' + String(m % 60).padStart(2, '0');
}
function prioRank(t) { return t.priority === 'High' ? 0 : t.priority === 'Medium' ? 1 : 2; }

function computeSchedule(formData) {
  const T = I18N.sched;
  const wake = toMin(formData.wakeTime);
  let sleep = toMin(formData.sleepTime);
  if (sleep <= wake) sleep += 1440;
  const workStart = toMin(formData.workStart);
  let workEnd = toMin(formData.workEnd);
  if (workEnd <= workStart) workEnd += 1440;
  const travelMinutes = Math.max(0, Number(formData.travelMinutes) || 0);

  const blocks = [];
  const cuts = [];
  const push = (s, e, activity, category, tag) => {
    if (e > s) blocks.push({ s, e, time: fmtTime(s) + ' - ' + fmtTime(e), activity, category, tag });
  };
  const fatigueSevere = formData.fatigue >= 7;
  const fatigueFactor = fatigueSevere ? 0.35 : formData.fatigue >= 5 ? 0.6 : 1;

  function fitQueue(queue, cursor, limit, windowLabel) {
    const leftover = [];
    queue.forEach((t) => {
      const avail = limit - cursor;
      if (avail <= 10) { leftover.push(t); return; }
      let dur = t.duration, tag = t.priority + ' Priority', adjusted = false;
      if (dur > avail || fatigueSevere) {
        const scaled = Math.max(10, Math.round(Math.min(avail, dur * fatigueFactor)));
        if (scaled < dur) {
          cuts.push({
            task: t.title,
            original: dur + ' ' + T.min,
            adjusted: scaled + ' ' + T.min + ' ' + T.shortened,
            reason: fatigueSevere ? T.reasonFatigue(formData.fatigue) : T.reasonLimited(windowLabel)
          });
          dur = scaled; adjusted = true; tag = 'Adjusted';
        }
      }
      push(cursor, cursor + dur, t.title + (adjusted ? T.adjSuffix : ''), 'Personal Growth', tag);
      cursor += dur;
    });
    return { cursor, leftover };
  }

  let mCursor = wake;
  push(mCursor, mCursor + 20, T.wake, 'Wellbeing', 'Health'); mCursor += 20;
  push(mCursor, mCursor + 25, T.breakfast, 'Routine', 'Life'); mCursor += 25;

  const morningWindowStart = mCursor;
  const morningWindowEnd = Math.max(mCursor, workStart - travelMinutes);
  const morningCapacity = morningWindowEnd - morningWindowStart;
  const eveningWindowStart = workEnd + travelMinutes;
  const eveningWindowEnd = Math.max(eveningWindowStart, sleep - 40);
  const eveningCapacity = eveningWindowEnd - eveningWindowStart;

  const allTasks = formData.tasks.filter((t) => t.type !== 'Work');
  const morningQueue = [], eveningQueue = [], autoQueue = [];
  allTasks.forEach((t) => {
    if (t.when === 'morning') morningQueue.push(t);
    else if (t.when === 'evening') eveningQueue.push(t);
    else autoQueue.push(t);
  });
  let simM = morningCapacity - morningQueue.reduce((s, t) => s + t.duration, 0);
  let simE = eveningCapacity - eveningQueue.reduce((s, t) => s + t.duration, 0);
  autoQueue.slice().sort((a, b) => prioRank(a) - prioRank(b)).forEach((t) => {
    if (simM >= simE) { morningQueue.push(t); simM -= t.duration; }
    else { eveningQueue.push(t); simE -= t.duration; }
  });
  morningQueue.sort((a, b) => prioRank(a) - prioRank(b));
  eveningQueue.sort((a, b) => prioRank(a) - prioRank(b));

  const morningResult = fitQueue(morningQueue, morningWindowStart, morningWindowEnd, T.morning);
  mCursor = morningResult.cursor;
  if (morningWindowEnd > mCursor) {
    push(mCursor, morningWindowEnd, T.freeMorning, 'Routine', 'Free Time');
    mCursor = morningWindowEnd;
  }
  if (workStart > mCursor) push(mCursor, workStart, T.commuteTo + (travelMinutes ? ' (~' + travelMinutes + ' ' + T.min + ')' : ''), 'Routine', 'Life');

  push(workStart, workEnd, T.work, 'Work', T.untouched);

  let eCursor = workEnd;
  if (eveningWindowStart > eCursor) push(eCursor, eveningWindowStart, T.commuteHome + (travelMinutes ? ' (~' + travelMinutes + ' ' + T.min + ')' : ''), 'Routine', 'Life');
  eCursor = eveningWindowStart;

  const combined = eveningQueue.concat(morningResult.leftover).sort((a, b) => prioRank(a) - prioRank(b));
  const eveningResult = fitQueue(combined, eCursor, eveningWindowEnd, T.evening);
  eCursor = eveningResult.cursor;
  eveningResult.leftover.forEach((t) => {
    cuts.push({ task: t.title, original: t.duration + ' ' + T.min, adjusted: T.skipped, reason: T.skipReason });
  });
  if (eCursor < eveningWindowEnd) {
    push(eCursor, eveningWindowEnd, T.dinner, 'Rest', 'Health');
    eCursor = eveningWindowEnd;
  }
  push(eCursor, sleep, T.detox, 'Sleep Prep', 'Rest');

  blocks.sort((a, b) => a.s - b.s);
  return { blocks, cuts, focusMinutes: workEnd - workStart };
}

// ---------------- Persistence ----------------
const PLAN_STORAGE_KEY = 'aiLifePlanner:lastPlan';
function loadSavedPlan() { try { const r = localStorage.getItem(PLAN_STORAGE_KEY); return r ? JSON.parse(r) : null; } catch (e) { return null; } }
function savePlan(p) { try { localStorage.setItem(PLAN_STORAGE_KEY, JSON.stringify(p)); } catch (e) {} }

// ---------------- Export ----------------
function downloadFile(filename, text, mime) {
  const blob = new Blob([text], { type: (mime || 'text/plain') + ';charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
function downloadSchedule() {
  const T = I18N.ui;
  if (!state.scheduleResult) { alert(T.noSchedule); return; }
  const lines = state.scheduleResult.blocks.map((b) => b.time + '  ' + b.activity + '  [' + b.category + ']');
  const cuts = state.scheduleResult.cuts;
  const text = T.txtTitle + '\n' + '='.repeat(40) + '\n\n' + lines.join('\n') + '\n\n' +
    (cuts.length ? T.txtCuts + '\n' + cuts.map((c) => '- ' + c.task + ': ' + c.original + ' -> ' + c.adjusted + ' (' + c.reason + ')').join('\n') : '');
  downloadFile('my-schedule.txt', text, 'text/plain');
}
function downloadCalendar() {
  if (!state.scheduleResult) { alert(I18N.ui.noSchedule); return; }
  const now = new Date();
  const y = now.getFullYear(), m = now.getMonth(), d = now.getDate();
  const pad = (n) => String(n).padStart(2, '0');
  const toICS = (mins) => {
    const dayOffset = Math.floor(mins / 1440);
    const mm = ((mins % 1440) + 1440) % 1440;
    const dt = new Date(y, m, d + dayOffset, Math.floor(mm / 60), mm % 60, 0);
    return dt.getFullYear() + pad(dt.getMonth() + 1) + pad(dt.getDate()) + 'T' + pad(dt.getHours()) + pad(dt.getMinutes()) + '00';
  };
  const stamp = now.getUTCFullYear() + pad(now.getUTCMonth() + 1) + pad(now.getUTCDate()) + 'T' + pad(now.getUTCHours()) + pad(now.getUTCMinutes()) + pad(now.getUTCSeconds()) + 'Z';
  const esc = (s) => String(s).replace(/([,;])/g, '\\$1');
  let ics = 'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//AI Life Planner//TH\r\nCALSCALE:GREGORIAN\r\n';
  state.scheduleResult.blocks.forEach((b, i) => {
    ics += 'BEGIN:VEVENT\r\nUID:ai-life-planner-' + Date.now() + '-' + i + '@local\r\nDTSTAMP:' + stamp +
      '\r\nDTSTART:' + toICS(b.s) + '\r\nDTEND:' + toICS(b.e) + '\r\nSUMMARY:' + esc(b.activity) +
      '\r\nCATEGORIES:' + esc(b.category) + '\r\nEND:VEVENT\r\n';
  });
  ics += 'END:VCALENDAR\r\n';
  downloadFile('my-schedule.ics', ics, 'text/calendar');
}
function printSchedule() {
  if (!state.scheduleResult) { alert(I18N.ui.noPrint); return; }
  window.print();
}

// ---------------- AI recommendations (optional) ----------------
const AI_KEY_STORAGE_KEY = 'aiLifePlanner:anthropicApiKey';
const AI_MODEL = 'claude-haiku-4-5';
function getStoredApiKey() { try { return localStorage.getItem(AI_KEY_STORAGE_KEY) || ''; } catch (e) { return ''; } }
function setStoredApiKey(key) {
  try { if (key) localStorage.setItem(AI_KEY_STORAGE_KEY, key); else localStorage.removeItem(AI_KEY_STORAGE_KEY); } catch (e) {}
}
async function getAIRecommendations(formData, cuts) {
  const apiKey = getStoredApiKey();
  if (!apiKey) return null;
  const anonTasks = formData.tasks.map((t) => anonymize(t.title) + ' (' + t.type + ', ' + t.priority + ', ' + t.duration + 'min)');
  const prompt = I18N.buildPrompt(formData, anonTasks, cuts);
  try {
    const res = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': apiKey,
        'anthropic-version': '2023-06-01',
        'anthropic-dangerous-direct-browser-access': 'true'
      },
      body: JSON.stringify({ model: AI_MODEL, max_tokens: 700, messages: [{ role: 'user', content: prompt }] })
    });
    if (!res.ok) return null;
    const data = await res.json();
    const text = (data.content || []).map((b) => b.text || '').join('');
    const parsed = JSON.parse(text.replace(/```json|```/g, '').trim());
    return parsed && parsed.fitness ? parsed : null;
  } catch (e) {
    console.warn('AI recommendation call failed, using offline fallback instead:', e);
    return null;
  }
}

// ---------------- State ----------------
let state = {
  activeTab: 'wizard',
  step: 1,
  formData: {
    wakeTime: '06:30', sleepTime: '23:00', workStart: '09:00', workEnd: '18:00',
    travelMinutes: 30,
    workStyle: I18N.workStyles[0],
    energy: 6, fatigue: 7, stress: 6,
    tasks: I18N.defaultTasks.map((t, i) => ({ id: i + 1, ...t, type: 'Personal', when: 'auto' }))
  },
  isGenerated: false,
  scheduleResult: null,
  apiKeyInput: getStoredApiKey()
};
function setState(patch) { state = { ...state, ...patch }; render(); }

// Typing only updates state (NO re-render), so inputs never lose focus
// and button clicks are never swallowed by a DOM rebuild.
function setTravel(el) {
  const raw = String(el.value).replace(/\D/g, '');
  state.formData.travelMinutes = raw === '' ? 0 : Math.min(180, parseInt(raw, 10));
}
function finishTravel(el) { el.value = state.formData.travelMinutes; }
function setSlider(key, el) {
  state.formData[key] = parseInt(el.value, 10);
  const label = document.getElementById('val-' + key);
  if (label) label.textContent = el.value + ' / 10';
}

function normalizeTimeInput(value) {
  let raw = String(value || '').trim();
  if (!raw) return '';
  if (raw.includes(':')) {
    const match = raw.match(/^(\d{1,2}):(\d{1,2})$/);
    if (!match) return '';
    const h = Number(match[1]), m = Number(match[2]);
    if (h > 23 || m > 59) return '';
    return String(h).padStart(2, '0') + ':' + String(m).padStart(2, '0');
  }
  raw = raw.replace(/\D/g, '');
  if (raw.length === 1 || raw.length === 2) {
    const h = Number(raw);
    if (h > 23) return '';
    return String(h).padStart(2, '0') + ':00';
  }
  if (raw.length === 3) raw = '0' + raw;
  if (raw.length > 4) raw = raw.slice(0, 4);
  if (raw.length !== 4) return '';
  const h = Number(raw.slice(0, 2)), m = Number(raw.slice(2, 4));
  if (h > 23 || m > 59) return '';
  return String(h).padStart(2, '0') + ':' + String(m).padStart(2, '0');
}
function setTimeField(key, el) {
  const normalized = normalizeTimeInput(el.value);
  if (normalized) state.formData[key] = normalized;
  el.value = state.formData[key];
}

function addPresetTask(idx) {
  const p = I18N.presets[idx];
  if (!p) return;
  state.formData.tasks = [...state.formData.tasks, { id: Date.now() + Math.random(), ...p, when: 'auto' }];
  render();
}
function addTask() {
  const titleEl = document.getElementById('newTaskTitle');
  const title = titleEl ? titleEl.value.trim() : '';
  if (!title) { if (titleEl) titleEl.focus(); return; }
  const duration = parseInt(document.getElementById('newTaskDuration').value) || 30;
  const priority = document.getElementById('newTaskPriority').value;
  const when = document.getElementById('newTaskWhen').value;
  state.formData.tasks = [...state.formData.tasks, { id: Date.now(), title, duration, priority, type: 'Personal', when }];
  render();
}
function removeTask(id) { state.formData.tasks = state.formData.tasks.filter((t) => t.id !== id); render(); }
function setTaskWhen(id, when) { state.formData.tasks = state.formData.tasks.map((t) => (t.id === id ? { ...t, when } : t)); render(); }

async function handleGeneratePlan() {
  const result = computeSchedule(state.formData);
  state.scheduleResult = { blocks: result.blocks, cuts: result.cuts, focusMinutes: result.focusMinutes, recommendations: null, aiStatus: 'loading' };
  state.isGenerated = true;
  state.activeTab = 'dashboard';
  render();
  const recs = await getAIRecommendations(state.formData, result.cuts);
  state.scheduleResult.recommendations = recs || I18N.fallback(state.formData);
  state.scheduleResult.aiStatus = recs ? 'ai' : 'fallback';
  render();
  savePlan({ formData: state.formData, scheduleResult: state.scheduleResult, savedAt: Date.now() });
}
function handleSaveApiKey() {
  const el = document.getElementById('apiKeyInput');
  const val = el ? el.value.trim() : '';
  setStoredApiKey(val);
  setState({ apiKeyInput: val });
}
function handleClearApiKey() { setStoredApiKey(''); setState({ apiKeyInput: '' }); }

// ---------------- Render ----------------
function navButton(id, label, iconSvg, disabled) {
  const active = state.activeTab === id;
  const cls = active ? 'bg-indigo-600 text-white shadow-md'
    : disabled ? 'text-slate-600 cursor-not-allowed'
    : 'text-slate-400 hover:text-slate-200 hover:bg-slate-800';
  return `<button ${disabled ? 'disabled' : ''} onclick="${disabled ? '' : `setState({activeTab:'${id}'})`}"
    class="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium transition ${cls}">${iconSvg}${label}</button>`;
}
function renderHeader() {
  const T = I18N.ui;
  return `
  <header class="no-print border-b border-slate-800 bg-slate-950/80 backdrop-blur sticky top-0 z-50 px-6 py-4 flex flex-wrap justify-between items-center" style="padding-top: calc(1rem + env(safe-area-inset-top, 0px));">
    <div class="flex items-center gap-3">
      <div class="bg-indigo-600 p-2 rounded-xl text-white shadow-lg shadow-indigo-500/30">${Icons.sparkles}</div>
      <div>
        <h1 class="font-bold text-xl tracking-tight bg-gradient-to-r from-indigo-400 to-cyan-400 bg-clip-text text-transparent">AI Life Planner & Dashboard</h1>
        <p class="text-xs text-slate-400">Time-Blocking & Lifestyle Architecture</p>
      </div>
    </div>
    <nav class="flex gap-2 mt-4 sm:mt-0 flex-wrap">
      ${navButton('wizard', T.navWizard, Icons.clock)}
      ${navButton('dashboard', T.navDash, Icons.calendar, !state.isGenerated)}
      ${navButton('privacy', T.navPrivacy, Icons.shield)}
    </nav>
  </header>`;
}

function timeInput(key, label, ph) {
  return `<div><label class="block text-xs font-medium text-slate-400 mb-1">${label}</label>
    <input type="text" inputmode="numeric" maxlength="5" placeholder="${ph}" value="${state.formData[key]}" onblur="setTimeField('${key}', this)" onkeydown="if(event.key==='Enter')this.blur()" class="w-full bg-slate-900 border border-slate-700 rounded-lg p-3 text-white focus:border-indigo-500 outline-none" /></div>`;
}
function slider(key, label, color, accent) {
  const f = state.formData;
  return `<div><div class="flex justify-between text-sm mb-1"><span>${label}</span><span id="val-${key}" class="font-bold ${color}">${f[key]} / 10</span></div>
    <input type="range" min="1" max="10" value="${f[key]}" oninput="setSlider('${key}', this)" class="w-full" ${accent ? `style="accent-color:${accent}"` : ''} /></div>`;
}

function renderWizard() {
  const f = state.formData, T = I18N.wizard;
  let inner = '';
  if (state.step === 1) {
    inner = `
    <div class="space-y-6">
      <h3 class="font-semibold text-lg text-cyan-300 flex items-center gap-2">${Icons.clock} ${T.s1Title}</h3>
      <div class="grid grid-cols-2 gap-4">
        ${timeInput('wakeTime', T.wake, T.phWake)}
        ${timeInput('sleepTime', T.sleep, T.phSleep)}
        ${timeInput('workStart', T.workStart, T.phWorkStart)}
        ${timeInput('workEnd', T.workEnd, T.phWorkEnd)}
        <div class="col-span-2"><label class="block text-xs font-medium text-slate-400 mb-1">${T.travel}</label>
          <input type="text" inputmode="numeric" pattern="[0-9]*" maxlength="3" value="${f.travelMinutes}" oninput="setTravel(this)" onblur="finishTravel(this)" onfocus="this.select()" class="w-full bg-slate-900 border border-slate-700 rounded-lg p-3 text-white focus:border-indigo-500 outline-none" />
          <p class="text-[11px] text-slate-500 mt-1">${T.travelHint}</p></div>
      </div>
      <div class="p-3 bg-indigo-950/30 border border-indigo-500/30 rounded-lg text-xs text-indigo-200">${T.workNote}</div>
      <div>
        <label class="block text-xs font-medium text-slate-400 mb-1">${T.workStyle}</label>
        <select onchange="state.formData.workStyle=this.value" class="w-full bg-slate-900 border border-slate-700 rounded-lg p-3 text-white focus:border-indigo-500 outline-none">
          ${I18N.workStyles.map((w) => `<option ${f.workStyle === w ? 'selected' : ''}>${w}</option>`).join('')}
        </select>
      </div>
      <button onclick="setState({step:2})" class="w-full py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg font-medium flex justify-center items-center gap-2 transition">${T.next1} ${Icons.arrow}</button>
    </div>`;
  } else if (state.step === 2) {
    inner = `
    <div class="space-y-6">
      <h3 class="font-semibold text-lg text-cyan-300 flex items-center gap-2">${Icons.heart} ${T.s2Title}</h3>
      <div class="space-y-4">
        ${slider('energy', T.energy, 'text-indigo-400')}
        ${slider('fatigue', T.fatigue, 'text-amber-400', '#f59e0b')}
        ${slider('stress', T.stress, 'text-rose-400', '#f43f5e')}
      </div>
      <div class="flex gap-4">
        <button onclick="setState({step:1})" class="w-1/3 py-3 bg-slate-700 hover:bg-slate-600 text-white rounded-lg font-medium">${T.back}</button>
        <button onclick="setState({step:3})" class="w-2/3 py-3 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg font-medium flex justify-center items-center gap-2">${T.next2} ${Icons.arrow}</button>
      </div>
    </div>`;
  } else {
    inner = `
    <div class="space-y-6">
      <h3 class="font-semibold text-lg text-cyan-300 flex items-center gap-2">${Icons.zap} ${T.s3Title}</h3>
      <p class="text-xs text-slate-500 -mt-4">${T.s3Hint}</p>
      <div class="space-y-3">
        ${f.tasks.map((t) => `
          <div class="p-3 bg-slate-900 border border-slate-700 rounded-lg flex justify-between items-center gap-2 flex-wrap">
            <div class="min-w-0">
              <span class="font-medium text-sm text-slate-200">${t.title}</span>
              <div class="flex gap-2 mt-1 flex-wrap"><span class="text-xs px-2 py-0.5 bg-indigo-950 text-indigo-300 rounded">${t.duration} ${I18N.sched.min}</span></div>
            </div>
            <div class="flex items-center gap-2 shrink-0">
              <select onchange="setTaskWhen(${t.id}, this.value)" title="${T.whenTitle}" class="text-xs bg-slate-800 border border-slate-700 rounded-lg px-2 py-1.5 text-slate-300">
                <option value="auto" ${!t.when || t.when === 'auto' ? 'selected' : ''}>🔀 ${T.auto}</option>
                <option value="morning" ${t.when === 'morning' ? 'selected' : ''}>🌅 ${T.morning}</option>
                <option value="evening" ${t.when === 'evening' ? 'selected' : ''}>🌙 ${T.evening}</option>
              </select>
              <span class="text-xs px-2 py-1 rounded font-medium ${t.priority === 'High' ? 'bg-rose-500/20 text-rose-300' : 'bg-slate-700 text-slate-300'}">${t.priority}</span>
              <button onclick="removeTask(${t.id})" title="${T.remove}" class="p-1.5 rounded-lg bg-slate-800 hover:bg-rose-500/20 text-slate-400 hover:text-rose-300 transition">${Icons.trash}</button>
            </div>
          </div>`).join('')}
        ${f.tasks.length === 0 ? `<p class="text-sm text-slate-500 text-center py-4">${T.noTasks}</p>` : ''}
      </div>
      <p class="text-[11px] text-slate-500 -mt-2">💡 ${T.autoHint}</p>

      <div class="p-4 bg-slate-900/40 border border-slate-800 rounded-xl space-y-3">
        <p class="text-xs font-semibold text-slate-400 uppercase tracking-wide">🌿 ${T.presets}</p>
        <div class="flex flex-wrap gap-2">
          ${I18N.presets.map((p, i) => `<button onclick="addPresetTask(${i})" class="text-xs px-3 py-1.5 rounded-full bg-emerald-950/50 border border-emerald-500/30 text-emerald-300 hover:bg-emerald-600 hover:text-white transition flex items-center gap-1">${Icons.plus} ${p.title} <span class="text-slate-400">· ${p.duration}${T.minShort}</span></button>`).join('')}
        </div>
      </div>

      <div class="p-4 bg-slate-900/60 border border-dashed border-slate-700 rounded-xl space-y-3">
        <p class="text-xs font-semibold text-slate-400 uppercase tracking-wide">${T.custom}</p>
        <input id="newTaskTitle" type="text" placeholder="${T.customPh}" class="w-full bg-slate-900 border border-slate-700 rounded-lg p-2.5 text-sm text-white focus:border-indigo-500 outline-none" />
        <div class="grid grid-cols-3 gap-2">
          <select id="newTaskDuration" class="bg-slate-900 border border-slate-700 rounded-lg p-2 text-xs text-white">
            ${[15, 30, 45, 60, 90, 120].map((d) => `<option value="${d}" ${d === 30 ? 'selected' : ''}>${d} ${I18N.sched.min}</option>`).join('')}
          </select>
          <select id="newTaskPriority" class="bg-slate-900 border border-slate-700 rounded-lg p-2 text-xs text-white">
            <option>High</option><option selected>Medium</option><option>Low</option>
          </select>
          <select id="newTaskWhen" class="bg-slate-900 border border-slate-700 rounded-lg p-2 text-xs text-white">
            <option value="auto" selected>🔀 ${T.auto}</option><option value="morning">🌅 ${T.morning}</option><option value="evening">🌙 ${T.evening}</option>
          </select>
        </div>
        <button onclick="addTask()" class="w-full py-2 bg-slate-700 hover:bg-indigo-600 text-white rounded-lg text-sm font-medium flex justify-center items-center gap-2 transition">${Icons.plus} ${T.addTask}</button>
      </div>

      <div class="flex gap-4 pt-4 border-t border-slate-700">
        <button onclick="setState({step:2})" class="w-1/3 py-3 bg-slate-700 hover:bg-slate-600 text-white rounded-lg font-medium">${T.back}</button>
        <button onclick="handleGeneratePlan()" class="w-2/3 py-3 bg-gradient-to-r from-indigo-600 to-cyan-600 hover:from-indigo-500 hover:to-cyan-500 text-white rounded-lg font-bold shadow-lg shadow-indigo-500/30 flex justify-center items-center gap-2">${Icons.sparkles} Generate Smart Life Schedule</button>
      </div>
    </div>`;
  }
  return `
  <div class="max-w-3xl mx-auto bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 sm:p-8 backdrop-blur shadow-xl">
    <div class="flex justify-between items-start gap-3 mb-6 border-b border-slate-700 pb-4">
      <div><h2 class="text-2xl font-bold text-indigo-300">${T.title}</h2><p class="text-slate-400 text-sm">${T.subtitle}</p></div>
      <span class="shrink-0 text-xs font-semibold px-3 py-1 bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 rounded-full">Step ${state.step} of 3</span>
    </div>
    ${inner}
  </div>`;
}

function renderChart(blocks) {
  const totals = {};
  blocks.forEach((b) => { totals[b.category] = (totals[b.category] || 0) + (b.e - b.s); });
  const total = Object.values(totals).reduce((a, c) => a + c, 0) || 1;
  const palette = ['#6366f1', '#22d3ee', '#f59e0b', '#f43f5e', '#10b981', '#a78bfa', '#eab308', '#38bdf8'];
  let acc = 0;
  const stops = [];
  const entries = Object.entries(totals).sort((a, b) => b[1] - a[1]);
  entries.forEach(([cat, val], i) => {
    const pct = (val / total) * 100;
    stops.push(`${palette[i % palette.length]} ${acc}% ${acc + pct}%`);
    acc += pct;
  });
  const legend = entries.map(([cat, val], i) =>
    `<div class="flex items-center gap-2 text-xs text-slate-300"><span class="w-3 h-3 rounded-full inline-block shrink-0" style="background:${palette[i % palette.length]}"></span>${cat} · ${Math.round((val / total) * 100)}% (${Math.round(val)} ${I18N.sched.min})</div>`).join('');
  return `<div class="flex items-center gap-6 flex-wrap">
    <div style="width:110px;height:110px;border-radius:50%;background:conic-gradient(${stops.join(',')});flex-shrink:0;"></div>
    <div class="space-y-1.5">${legend}</div></div>`;
}

function renderDashboard() {
  if (!state.scheduleResult) return '';
  const T = I18N.dash;
  const { blocks, cuts, recommendations, aiStatus, focusMinutes } = state.scheduleResult;
  const focusHours = (focusMinutes / 60).toFixed(1);
  const badge = (cls, ic, txt) => `<span class="inline-flex items-center gap-1.5 text-xs px-2.5 py-1 rounded-full ${cls}">${ic} ${txt}</span>`;
  const aiBadge = aiStatus === 'loading' ? badge('bg-slate-800 border border-slate-700 text-slate-400', Icons.robot, T.badgeLoading)
    : aiStatus === 'ai' ? badge('bg-emerald-500/15 border border-emerald-500/30 text-emerald-300', Icons.sparkles, T.badgeAi)
    : badge('bg-amber-500/15 border border-amber-500/30 text-amber-300', Icons.alert, T.badgeOffline);
  const dims = recommendations ? [
    { title: '1. Fitness & Movement', icon: Icons.dumbbell, color: 'emerald', text: recommendations.fitness },
    { title: '2. Nutrition & Rest', icon: Icons.heart, color: 'amber', text: recommendations.nutrition },
    { title: '3. Mental Wellbeing', icon: Icons.brain, color: 'cyan', text: recommendations.mental },
    { title: '4. Personal Growth', icon: Icons.zap, color: 'indigo', text: recommendations.growth }
  ] : [];
  const high = state.formData.fatigue >= 7;
  return `
  <div class="max-w-5xl mx-auto space-y-8">
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6 no-print">
      <div class="bg-slate-800/80 border border-slate-700/80 p-5 rounded-xl">
        <div class="flex items-center gap-3 mb-2">${Icons.heart}<span class="text-sm font-semibold text-slate-300">${T.readiness}</span></div>
        <div class="text-2xl font-bold text-white">Fatigue: ${state.formData.fatigue}/10</div>
        <p class="text-xs ${high ? 'text-amber-400' : 'text-emerald-400'} mt-1">${high ? T.fatigueHigh : T.fatigueOk}</p>
      </div>
      <div class="bg-slate-800/80 border border-slate-700/80 p-5 rounded-xl">
        <div class="flex items-center gap-3 mb-2">${Icons.clock}<span class="text-sm font-semibold text-slate-300">${T.workHours}</span></div>
        <div class="text-2xl font-bold text-indigo-300">${focusHours} ${T.hours}</div>
        <p class="text-xs text-emerald-400 mt-1">${T.workReserved}</p>
      </div>
      <div class="bg-slate-800/80 border border-slate-700/80 p-5 rounded-xl">
        <div class="flex items-center gap-3 mb-2">${Icons.brain}<span class="text-sm font-semibold text-slate-300">Smart Cut Efficiency</span></div>
        <div class="text-2xl font-bold text-cyan-300">${cuts.length} Tasks Adjusted</div>
        <p class="text-xs text-slate-400 mt-1">${T.cutNote}</p>
      </div>
    </div>
    ${cuts.length ? `
    <div class="bg-amber-950/40 border border-amber-500/40 p-5 rounded-xl no-print">
      <h3 class="font-semibold text-amber-300 flex items-center gap-2 mb-3">${Icons.alert} Smart Cut & Dynamic Task Adjustment Log</h3>
      <div class="space-y-2">
        ${cuts.map((c) => `<div class="text-sm bg-slate-900/60 p-3 rounded-lg border border-amber-500/20">
          <div class="flex justify-between font-medium text-amber-200 flex-wrap gap-1"><span>${c.task}</span><span>${c.original} ➔ <span class="text-emerald-400">${c.adjusted}</span></span></div>
          <p class="text-xs text-slate-400 mt-1">${T.reason} ${c.reason}</p></div>`).join('')}
      </div>
    </div>` : ''}
    <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 backdrop-blur" id="printArea">
      <div class="flex justify-between items-center mb-6 flex-wrap gap-3">
        <h3 class="font-bold text-xl text-white flex items-center gap-2">${Icons.calendar} ${T.scheduleTitle}</h3>
        <div class="flex flex-wrap gap-2 no-print">
          <button onclick="downloadSchedule()" class="flex items-center gap-2 text-xs font-medium px-3 py-2 bg-slate-700 hover:bg-indigo-600 text-white rounded-lg transition">${Icons.download} .txt</button>
          <button onclick="printSchedule()" class="flex items-center gap-2 text-xs font-medium px-3 py-2 bg-slate-700 hover:bg-indigo-600 text-white rounded-lg transition">${Icons.download} ${T.pdf}</button>
          <button onclick="downloadCalendar()" class="flex items-center gap-2 text-xs font-medium px-3 py-2 bg-slate-700 hover:bg-indigo-600 text-white rounded-lg transition">${Icons.download} ${T.cal}</button>
        </div>
      </div>
      <div class="space-y-3">
        ${blocks.map((b) => `<div class="flex flex-col sm:flex-row items-start sm:items-center justify-between p-4 bg-slate-900/80 border border-slate-800 rounded-xl hover:border-slate-700 transition">
          <div class="flex items-center gap-4"><span class="text-sm font-mono font-semibold text-indigo-400 w-32 shrink-0">${b.time}</span>
            <div><div class="font-medium text-slate-200">${b.activity}</div><span class="text-xs text-slate-500">${b.category}</span></div></div>
          <span class="mt-2 sm:mt-0 text-xs font-semibold px-2.5 py-1 rounded-full bg-slate-800 border border-slate-700 text-cyan-300">${b.tag}</span>
        </div>`).join('')}
      </div>
    </div>
    <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 backdrop-blur no-print">
      <h3 class="font-bold text-lg text-white mb-4">${T.alloc}</h3>
      ${renderChart(blocks)}
    </div>
    <div class="no-print">
      <div class="flex items-center justify-between mb-4 flex-wrap gap-2">
        <h3 class="font-bold text-lg text-white">${T.recs}</h3>${aiBadge}
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        ${aiStatus === 'loading'
          ? `<div class="md:col-span-2 bg-slate-800/60 border border-slate-700/60 p-6 rounded-xl text-center text-slate-400 text-sm flex items-center justify-center gap-2"><span class="spin inline-block">${Icons.refresh}</span> ${T.generating}</div>`
          : dims.map((d) => `<div class="bg-slate-800/60 border border-slate-700/60 p-6 rounded-xl">
          <h4 class="font-semibold text-${d.color}-400 flex items-center gap-2 mb-3">${d.icon} ${d.title}</h4>
          <p class="text-sm text-slate-300">${d.text}</p></div>`).join('')}
      </div>
    </div>
  </div>`;
}

function renderPrivacy() {
  const T = I18N.privacy;
  const liveTasks = state.formData.tasks.map((t) => `<div class="grid grid-cols-2 gap-2 text-xs font-mono py-1.5 border-b border-slate-800/60 last:border-0">
    <span class="text-slate-400 break-words">${t.title}</span><span class="text-emerald-400 break-words">${anonymize(t.title)}</span></div>`).join('');
  const hasKey = !!getStoredApiKey();
  return `
  <div class="max-w-3xl mx-auto space-y-6">
    <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 sm:p-8 backdrop-blur space-y-6">
      <div class="flex items-center gap-3 border-b border-slate-700 pb-4">
        <div class="text-emerald-400">${Icons.shield}</div>
        <div><h2 class="text-xl font-bold text-white">Privacy-First Data Shield</h2><p class="text-sm text-slate-400">${T.shieldSub}</p></div>
      </div>
      <div>
        <h4 class="font-semibold text-slate-300 text-sm mb-2">${T.tableTitle}</h4>
        <div class="bg-slate-950 p-3 rounded-lg border border-slate-800">
          <div class="grid grid-cols-2 gap-2 text-xs font-semibold text-slate-500 pb-1 border-b border-slate-800"><span>${T.raw}</span><span>${T.anon}</span></div>
          ${liveTasks || `<p class="text-xs text-slate-500 py-2">${T.empty}</p>`}
        </div>
      </div>
      <div class="p-4 bg-emerald-950/30 border border-emerald-500/30 rounded-xl text-xs text-emerald-200">✓ ${T.shieldNote}</div>
    </div>

    <div class="bg-slate-800/60 border border-slate-700/60 rounded-2xl p-6 sm:p-8 backdrop-blur space-y-4">
      <div class="flex items-center gap-3 border-b border-slate-700 pb-4">
        <div class="text-indigo-400">${Icons.key}</div>
        <div><h2 class="text-xl font-bold text-white">${T.aiTitle}</h2><p class="text-sm text-slate-400">${T.aiSub}</p></div>
      </div>
      <div class="space-y-3">
        <label class="block text-xs font-medium text-slate-400">Anthropic API Key</label>
        <input id="apiKeyInput" type="password" placeholder="sk-ant-..." value="${state.apiKeyInput || ''}" class="w-full bg-slate-900 border border-slate-700 rounded-lg p-3 text-sm text-white font-mono focus:border-indigo-500 outline-none" />
        <div class="flex gap-3">
          <button onclick="handleSaveApiKey()" class="flex-1 py-2.5 bg-indigo-600 hover:bg-indigo-500 text-white rounded-lg text-sm font-medium">${T.save}</button>
          <button onclick="handleClearApiKey()" class="flex-1 py-2.5 bg-slate-700 hover:bg-rose-600 text-white rounded-lg text-sm font-medium">${T.clear}</button>
        </div>
        <p class="text-xs ${hasKey ? 'text-emerald-400' : 'text-slate-500'}">${hasKey ? T.keyFound : T.keyNone}</p>
        <div class="p-3 bg-amber-950/30 border border-amber-500/30 rounded-lg text-xs text-amber-200">⚠️ ${T.keyWarn}</div>
      </div>
    </div>
  </div>`;
}

function render() {
  let main = '';
  if (state.activeTab === 'wizard') main = renderWizard();
  else if (state.activeTab === 'dashboard') main = renderDashboard();
  else if (state.activeTab === 'privacy') main = renderPrivacy();
  document.getElementById('app').innerHTML = `
    <div class="min-h-screen bg-slate-900 text-slate-100 pb-12">
      ${renderHeader()}
      <main class="max-w-7xl mx-auto px-4 sm:px-6 mt-8">${main}</main>
    </div>`;
}

(function boot() {
  render();
  const saved = loadSavedPlan();
  if (saved && saved.formData && saved.scheduleResult) {
    state.formData = saved.formData;
    state.scheduleResult = saved.scheduleResult;
    state.isGenerated = true;
    state.activeTab = 'dashboard';
    render();
  }
})();
